### ISSUE TITLE
No passwd entry for user '10002'

### ISSUE THREAD

**Issue by Ryan-J-D** [Sinusbot/installer-linux#21]
Installing necessary packages! Please wait...
Packages installed!
TS3 already latest version.
Downloading latest SinusBot.
No passwd entry for user '10002'
Error on line 683. Report this to the author at https://forum.sinusbot.com/threads/sinusbot-installer-script.1200/ only. Not a PN or a bad review, cause this is an error of your system not of the installer script. Or have a look directly to your error: https://github.com/Sinusbot/installer-linux/blob/master/sinusbot_installer.sh#L683

**Comment by DAThosting** [comment]
Which OS?
Can't reproduce this. The user havn't got a password and doesn't need one.
