### ISSUE TITLE
Error on line 904

### ISSUE THREAD

**Issue by ReactiioN1337** [Sinusbot/installer-linux#26]
```
Can't set your date automatically. Please follow the following steps:
Day    (1-32): 12
Month  (1-12): 7
Year   (2017): 2017
Hour   (0-23): 22
Minute (0-60): 34
Second (0-60):10
date: invalid date ‘1272017’
```

Error on line 904. Report this to the author at https://forum.sinusbot.com/threads/sinusbot-installer-script.1200/ only. Not a PN or a bad review, cause this is an error of your system not of the installer script. Or have a look directly to your error: https://github.com/Sinusbot/installer-linux/blob/master/sinusbot_installer.sh#L904

**Comment by anton101101** [comment]
Also getting this error.

 Ubuntu 16.04.2 LTS

**Comment by Provokan** [comment]
Fraglich warum er die das Datum und die Uhrzeit wissen will 🗡

**Comment by Provokan** [comment]
Selbst nach dem vermeindlichen "ubuntu" fix funktioniert es nicht der Zeit, wofür wird dies überhaupt benötigt?

**Comment by maxibanki** [comment]
Test

**Comment by mxschmitt** [comment]
Die Uhrzeit wird wegen dem Lizenzserver benötigt. Wenn die um nur ein paar 
Sekunden ungenau ist, schlägt die Anfrage fehl und der SinusBot startet nicht.

**Comment by Provokan** [comment]
Maxi so richtig ist dies nicht. :) Nachdem ich die Zeit auf 2 Sec unterschied eingetippt habe auch fehlgeschlagen ist?

Day    (01-32): 16
Month  (01-12): 7
Year   (2017):  2017
Hour   (0-23):  22
Minute (0-60):  07
Second (0-60):  02
date: invalid date ‘2017716’
