### ISSUE TITLE
Cant Update my Sinusbot

### ISSUE THREAD

**Issue by ChaosToaster** [Sinusbot/installer-linux#31]
Hello Guys,

i have a big Problem, i need to Update my Bot cause hes not running as a few weeks but i got an error:

```
TS3 client install done.
Downloading latest SinusBot.
Extracting SinusBot files.
SinusBot installation done.
Starting systemd installation
Failed to stop sinusbot.service: Unit sinusbot.service not loaded.
Error on line 815. Report this to the author at https://forum.sinusbot.com/threads/sinusbot-installer-script.1200/ only. Not a PN or a bad review, cause this is an error of your system not of the installer script. Or have a look directly to your error: https://github.com/Sinusbot/installer-linux/blob/master/sinusbot_installer.sh#L815
```

I make a fresh and new install with the installer Script. Can ya help me?

**Comment by DAThosting** [comment]
More Informations please...
OS? KVM or OpenVZ virtualization?

You could backup your data folder, delete the bot with the installer and install it again.
Stop the bot, switch back the backupped data folder, set permissions and restart the bot.

**Comment by ChaosToaster** [comment]
Root Server, Linux Debian Jessie, All Updated and Upgraded.

I cant make a Backup cause i delete the Old Bot

**Comment by DAThosting** [comment]
You wrote "i need to Update"...

You havn't deleted it with the installer...
Manual I guess?
Look at line 815 and follow the if clause.

**Comment by ChaosToaster** [comment]
Now i install it manually but i got the next Error:

`sinusbot@Debian-86-jessie-64-LAMP:/opt/sinusbot$ ./sinusbot
Could not open /tmp/.sinusbot.lock. Is SinusBot already running?
sinusbot@Debian-86-jessie-64-LAMP:/opt/sinusbot$
`
And can u maybe speak German?

**Comment by DAThosting** [comment]
Wir von Sinusbot sind alle deutschsprachig ^^

Lösche diese Datei.

**Comment by ChaosToaster** [comment]
OMG Gott sei Dank :D jedes mal wenn Ihr ein Update macht habe ich extreme Probleme mit diesem Bot. So langsam lerne ich Ihn zu hassen ^^
Ich liebe dich jetzt schon ^^ er funktioniert.
Jetzt brauch ich nur noch ein funktionierendes Startscript, am besten eins, was man direkt im Ordner ausführen kann. Ich hatte mal eins in einer launch.sh gepackt aber das hab ich leider nicht mehr. Hast du da evtl. etwas für mich, weil das standart Startscript ist Dreck ^^

**Comment by DAThosting** [comment]
Das ist nicht der Bot, sondern die (muss man leider sagen) günstigen und schlecht funktionierenden Systeme billiger Hoster.

Im Installer ist ein Script dabei.

Einfach als root "service sinusbot start" ausführen.

"Dreck" ist keines der Scripte.

**Comment by ChaosToaster** [comment]
Ja schon klar aber das Startscript ist echt mist. Hab mein altes wieder gefunden bei euch im Forum aber ich habe trotzdem ein Problem undzwar kann er es nicht ausführen da er mir folgendes ausspuckt:

You are not the owner of /var/run/screen/S-sinusbot.
sinusbot started successfully

**Comment by DAThosting** [comment]
Das ist nicht mein Problem ;)

Nutze das neue, es funktioniert problemlos, was soll denn daran schlecht sein?

Oder schreibe dir eins selbst ^^

**Comment by Xuxe** [comment]
Systemd is since debian jessie standard for ubuntu 16.04 to. 
I don't know whats the problem for you with systemd?

**Comment by ChaosToaster** [comment]
It works now :) <3
