### ISSUE TITLE
Error on line 1096

### ISSUE THREAD

**Issue by Grischabock** [Sinusbot/installer-linux#33]
2017/11/04 07:08:53 X [MAIN] Starting up fake x-server...
 ___ ___ _  _ _   _ ___ ___  ___ _____  BETA
/ __|_ _| \| | | | / __| _ )/ _ \_   _|
\__ \| || .` | |_| \__ \ _ \ (_) || |
|___/___|_|\_|\___/|___/___/\___/ |_|

Version: 0.10.8-71ba94b
(C) 2013-2017 Michael Friese. All rights reserved.

2017/11/04 07:08:53 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin advertising.js
2017/11/04 07:08:53 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin alonemode.js
2017/11/04 07:08:53 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin bookmark.js
2017/11/04 07:08:53 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin followme.js
2017/11/04 07:08:53 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin norecording.js
2017/11/04 07:08:53 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin rememberChannel.js
2017/11/04 07:08:53 [GENERAL/SCRIPTS] INFO   Loading ScriptPlugin welcome.js
a manual update is required
Error on line 1096. Report this to the author at https://forum.sinusbot.com/threads/sinusbot-installer-script.1200/ only. Not a PN or a bad review, cause this is an error of your system not of the installer script. Or have a look directly to your error: https://github.com/Sinusbot/installer-linux/blob/master/sinusbot_installer.sh#L1096

**Comment by mxschmitt** [comment]
Your time on your server could be not correct. Try to set it with a ntp by using:
```
apt-get install ntp
ntpd -q -g
hwclock --systohc
```
If this isn't working, provide us the output of the diagnostic script from [here](https://forum.sinusbot.com/threads/diagsinusbot-sh-sinusbot-diagnostic-script.831/).

**Comment by mxschmitt** [comment]
Since you have not answered two days now, I assume that the problem has been solved and I will close the issue.
