### ISSUE TITLE
Error on line 66.

### ISSUE THREAD

**Issue by fddn** [Sinusbot/installer-linux#36]
When I tried to install Sinusbot with this script, everything worked fine until the script reached "Checking for the latest latest installer version" state.
I get this error: 
"Checking for the latest latest installer version
Error on line 66. Report this to the author at https://forum.sinusbot.com/threads/sinusbot-installer-script.1200/ only. Not a PN or a bad review, cause this is an error of your system not of the installer script. Or have a look directly to your error: https://github.com/Sinusbot/installer-linux/blob/master/sinusbot_installer.sh#L66"

Error cames after this:
" Searching latest TS3-Client build for hardware type x86_64 with arch amd64.
Could not detect latest TS3-Client version "

I tried to run the code manually, download the client, but nothing.
Please look after this error.

OS: Ubuntu 16.04 LTS

Thanks! :)

**Comment by mxschmitt** [comment]
Please execute the commands and see which one is not working or will throw an error:
- `wget --no-check-certificate --timeout=60 -qO - https://raw.githubusercontent.com/SinusBot/installer-linux/master/sinusbot_installer.sh`
- `wget --no-check-certificate --timeout=60 -qO - https://raw.githubusercontent.com/SinusBot/installer-linux/master/sinusbot_installer.sh | grep -Po '(?<=Instversion=")([0-9]\.[0-9]+)`

**Comment by fddn** [comment]
Tried already. No success.

**Comment by mxschmitt** [comment]
Try this one. Maybe so we can see why the command fails:
`wget --no-check-certificate --timeout=60 https://raw.githubusercontent.com/SinusBot/installer-linux/master/sinusbot_installer.sh`

**Comment by fddn** [comment]
Tried, nothing.

But.
I figured out what was the problem.
The ISP couldn't resolve some hostnames. After I checked this manually everything was good.
So I contacted with the ISP, they updated the rules, and everything is working right now.
