### ISSUE TITLE
Error on line 684.

### ISSUE THREAD

**Issue by Tinoxy** [Sinusbot/installer-linux#42]
Starting the installer now!
Updating the system in a few seconds!
This could take a while. Please wait up to 10 minutes!
Searching latest TS3-Client build for hardware type x86_64 with arch amd64.
Detected latest TS3-Client version as 3.1.7
Installing necessary packages. Please wait...
E: Unable to locate package iproute2
Error on line 684. Report this to the author at https://forum.sinusbot.com/threads/sinusbot-installer-script.1200/ only. Not a PN or a bad review, cause this is an error of your system not of the installer script.
Failed command: https://github.com/Sinusbot/installer-linux/blob/master/sinusbot_installer.sh#L684

Error on line 684. Report this to the author at https://forum.sinusbot.com/threads/sinusbot-installer-script.1200/ only. Not a PN or a bad review, cause this is an error of your system not of the installer script.
Failed command: https://github.com/Sinusbot/installer-linux/blob/master/sinusbot_installer.sh#L684

**Comment by mxschmitt** [comment]
Which linux distribution?
Please run the diagScript by executing:
`wget -O - https://raw.githubusercontent.com/patschi/sinusbot-tools/master/tools/diagSinusbot.sh | bash`

**Comment by mxschmitt** [comment]
I'm closing this right now, because we don't get any information for over a week.
