### ISSUE TITLE
Teamspeak Version

### ISSUE THREAD

**Issue by ghost** [Sinusbot/installer-linux#53]
The official tutorial on how to install it uses a different version of Teamspeak, why aren't we able to choose which one we want? https://github.com/flyth/ts3soundbot/wiki/Installation---Debian-&-Ubuntu

**Comment by DAThosting** [comment]
First of all, your provided link is an old introduction, as you can see on top of the file "An updated version on...".Next our script always uses the latest ts client for the best function with SinusBot, why we should add an option for choosing the ts clients version? That is not really user friendly and unnecessary :)
