### ISSUE TITLE
Test Ubuntu 18.04 installation

### ISSUE THREAD

**Issue by mxschmitt** [Sinusbot/installer-linux#57]

**Comment by DAThosting** [comment]
In progress

**Comment by Allesanddro** [comment]
Ubuntu18.04 https://i.sandrotracker.biz/2feba2412ee5d688e75ef9164c5f6f45.png Install failed.
Failed to restart ntp.service: Unit ntp.service is masked.

Machine: Ubuntu 18.04 | Dedicated | Linux homeserver 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Allesanddro** [comment]
kinda "fresh" install 2 weeks ago
