### ISSUE TITLE
Could not detect latest TS3-Client version

### ISSUE THREAD

**Issue by Thumpxr** [Sinusbot/installer-linux#58]
Neither Teamspeak nor Sinusbot can be updates due to this error:

Could not detect latest TS3-Client version

**Comment by Thumpxr** [comment]
Due to server 3.2.0 beeing out and only client 3.1.9.

Perhaps there should be a check where the latest is only a server release?

**Comment by irgendwr** [comment]
Should be fixed with the new update, would be nice if you could test it.

**Comment by Thumpxr** [comment]
Although its a pretty bad workaround, it works.
Would be nicer if it checked whether or not the filename included "server".

**Comment by irgendwr** [comment]
We're open to pull requests if you wanna' give it a try.

**Comment by DAThosting** [comment]
Should be fixed in https://github.com/SinusBot/installer-linux/commit/c2ede605e5aee5742057212e003998e4fe7ed67c
Available if sinusbot supports newer versions of ts than 3.1.9!
