### ISSUE TITLE
Incorrect cron entry for ytdl updates

### ISSUE THREAD

**Issue by NielsH** [Sinusbot/installer-linux#61]
Hello,

The SinusBot installer script installs ytdl and adds a cron-entry to automatically update this tool. It does that by creating `/etc/cron.d/ytdl` which contains:
```
0 0 * * * sinusbot youtube-dl -U --restrict-filename >/dev/null
```
However, on Debian 8 at least, this cron fails. This is because `youtube-dl` is located in `/usr/local/bin/youtube-dl` and the default `PATH` in the cron file is `/usr/bin:/bin`.

I fixed it for now by changing the cron to this:
```
0 0 * * * sinusbot PATH=$PATH:/usr/local/bin; youtube-dl -U --restrict-filename >/dev/null
```

However, I am not sure if the cron can be overwritten automatically by an update from SinusBot at some point, which is why I am reporting it here.

**Comment by DAThosting** [comment]
Fixed with https://github.com/SinusBot/installer-linux/commit/466a94c4bb03a0e10162a33ab67d35fb5621ad47
