### ISSUE TITLE
Clear warning before deleting directory

### ISSUE THREAD

**Issue by irgendwr** [Sinusbot/installer-linux#63]
Someone deleted his home folder by accident (see [discord chat](https://discordapp.com/channels/152947849393471488/452450263702306817/516237590953852949)). 
Congratulations, I think he is the first one to do this out of thousands of users 🎉 

Although **the script is not to blame** for this since it asks for the location and a confirmation, the warning should be improved to _clearly state that all data in this location will be deleted_.

<img height="300px" src="https://memegenerator.net/img/instances/66714839/fuck-linux.jpg" alt="fuck linux meme">

**Comment by DAThosting** [comment]
There are a bunch of funny guys out there, but he rocked the shit! ^^
2018-11-25 5:05pm 210362 downloads without this problem ^^

Fixed in https://github.com/SinusBot/installer-linux/commit/5e329699d7562e768df74c7ad390417a7d22e2cd
