### ISSUE TITLE
i get a fail what can i do

### ISSUE THREAD

**Issue by M4Ri3DE** [Sinusbot/installer-linux#66]
Command which failed was: "    apt-get update". Please try to execute it manually                                                                                and attach the output to the bug report in the forum thread.
If it still doesn't work report this to the author at https://forum.sinusbot.com/                                                                               threads/sinusbot-installer-script.1200/ only. Not a PN or a bad review, cause thi                                                                               s is an error of your system not of the installer script. Line 266.

**Comment by mxschmitt** [comment]
Please provide us the entire output of the Script starting at script execution. Mostly this error occurs, when you have a broken apt. (Use Google, Stackoverflow etc. how you can fix that)

**Comment by M4Ri3DE** [comment]
Yes i will send it tomorrow but that comes only when i use the install Option 

Von meinem iPhone gesendet

**Comment by mxschmitt** [comment]
Closed due inactivity
