### ISSUE TITLE
Could not detect latest TS3-Client version

### ISSUE THREAD

**Issue by Bl4CkGuuN** [Sinusbot/installer-linux#74]
Hey, tried to install sinusbot with the installer on my Ubuntu 18.04.3 system and got this error:

![image](https://user-images.githubusercontent.com/22998615/70745595-65abaf80-1d24-11ea-896a-f139068d73b2.png)

**Comment by Bl4CkGuuN** [comment]
seems like that #VERSION is not working.
As a workaround I just changed the link to the newest ts3 release.
![image](https://user-images.githubusercontent.com/22998615/70746998-4a8e6f00-1d27-11ea-84a8-1fbc6a32d780.png)

**Comment by mxschmitt** [comment]
@Bl4CkGuuN issue is fixed, sorry for the inconvenience. We migrated to a new website: https://sinusbot.github.io/installer/
