### ISSUE TITLE
[Feature Request] Allow Setting Securitylevel of Teamspeak identities

### ISSUE THREAD

**Issue by WebsiteDeveloper** [Sinusbot/installer-linux#77]

**Comment by DAThosting** [comment]
Already included in webinterface...

**Comment by WebsiteDeveloper** [comment]
Could you point me in the right direction?
Because for me the security level is always greyed out in the webinterface

**Comment by irgendwr** [comment]
https://sinusbot.github.io/docs/installation/increase-security-level/
