### ISSUE TITLE
[Feature Request] Optionally install nginx install and config including letsencrypt cert

### ISSUE THREAD

**Issue by WebsiteDeveloper** [Sinusbot/installer-linux#78]

**Comment by DAThosting** [comment]
Why we should include that?
A webserver is not needed to install SinusBot.

**Comment by WebsiteDeveloper** [comment]
True it is not needed
But it would allow for Login and traffic to be encrypted and also for users to access the bot without using a port in the URL
That's why it was my suggestion to add it as an optional feature

**Comment by irgendwr** [comment]
I don't think that this would be a huge benefit for the following reasons:
- we already have instructions that are simple enough imo: https://sinusbot.github.io/docs/reverse-proxy/nginx/
- users still need to manually create a subdomain
- this would probably create more support requests

Closing this for now but thanks for the idea :)
