### ISSUE TITLE
Script doesn't work in IPv6 only environments

### ISSUE THREAD

**Issue by pyramidenkoenig** [Sinusbot/installer-linux#83]
Hi, i noticed that this script is unusable in an IPv6 only environment. This is probably due to Github not supporting IPv6. Even after i replaced the download sources with links to a Dualstack Server hosting copies of those files, i can't seem to get it to work. It fails at `Downloading TS3 client files.
Download failed! Exiting now!
`
Any ideas on how to get this working? What do i need to change?
I'd love to use this script more often, but due to most of my VMs being IPv6 only, i sadly can't.

Thanks.

**Comment by mxschmitt** [comment]
We don't support ipv6 only environments since thats not common. Sorry.

**Comment by xCuzImPro** [comment]
Download mit einem ipv6 vserver :(
