### ISSUE TITLE
Update TS3 version?

### ISSUE THREAD

**Issue by irgendwr** [Sinusbot/installer-linux#84]
Should we bump the TS3 client version?

**Comment by mxschmitt** [comment]
Is it `3.5.2` compatible?

https://github.com/SinusBot/installer-linux/blob/7864ac329824e57d788e49a89509c67df9307944/sinusbot_installer.sh#L602-L604

**Comment by irgendwr** [comment]
> Is it 3.5.2 compatible?

I have not tested it but @fabm3n and a few others said if works, dunno.

**Comment by fabm3n** [comment]
Don't had any issues with 3.5.2 and I'm using it since the release date (2nd April 2020).
I support the version bump.
